### ISSUE TITLE
crash with chunk multi draw enabled

### ISSUE THREAD

**Issue by justaguywhowantsminecraftmods** [ChlorineMC/Carbon-Mod#1]
crash when enabling this option. fixed when using the jvm argument -Dorg.lwjgl.util.NoChecks=true
I had the same issue in angelica which I think was determined to be an intel igpu issue and was fixed in alpha35 if that helps at all

**Comment by refactorinqq** [comment]
This is not a fault with the mod. Your GPU is way too old.
